server:
  port: 9100

spring:
  application:
    name: Server
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/sanuser
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
          url: jdbc:mysql://localhost:3306/microservice
          username: root
          password: admin
          driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1100/eureka/